2.6.32.30 last minute change (after rc0) broke:
/media/data/mattems/src/linux-2.6-2.6.32/debian/build/source_amd64_none/lib/swiotlb.c: In function ‘swiotlb_map_page’:
/media/data/mattems/src/linux-2.6-2.6.32/debian/build/source_amd64_none/lib/swiotlb.c:635: error: implicit declaration of function ‘swiotlb_tbl_unmap_single’

add proposed fix.

svn path=/dists/squeeze/linux-2.6/; revision=16970